CREATE DATABASE  GROCERYSTORE;
USE GROCERYSTORE;
-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
DESC SUPPLIER;
-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
 DESC CATEGORIES;
-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);
DESC EMPLOYEES;
-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);
DESC CUSTOMERS;
-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
DESC PRODUCTS;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
DESC ORDERS;
-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
DESC ORDER_DETAILS;
#Analysis Questions
#1. Customer Insights

#-- How many unique customers have placed orders?

SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

#--  Which customers have placed the highest number of orders?

SELECT c.cust_name, COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id
ORDER BY total_orders DESC;


# --What is the total and average purchase value per customer?

SELECT c.cust_name,
       SUM(od.total_price) AS total_purchase,
       AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id
ORDER BY total_purchase DESC;

# -- Who are the top 5 customers by total purchase amount?
SELECT c.cust_name, SUM(od.total_price) AS total_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id
ORDER BY total_purchase DESC
LIMIT 5;




# 2. Product Performance
#-- How many products exist in each category?

SELECT cat.cat_name, COUNT(p.prod_id) AS num_products
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_id;

#-- What is the average price of products by category?

SELECT cat.cat_name, AVG(p.price) AS avg_price
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_id;


#--Which products have the highest total sales volume (by quantity)?

SELECT p.prod_name, SUM(od.quantity) AS total_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id
ORDER BY total_quantity DESC;

#--What is the total revenue generated by each product?

SELECT p.prod_name, SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id
ORDER BY total_revenue DESC;

#-- How do product sales vary by category and supplier?

SELECT cat.cat_name, s.sup_name, SUM(od.total_price) AS total_revenue
FROM products p
JOIN categories cat ON p.cat_id = cat.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY cat.cat_id, s.sup_id
ORDER BY total_revenue DESC;




# 3. Sales and Order Trends
#-- How many orders have been placed in total?

SELECT COUNT(*) AS total_orders
FROM orders;

#-- What is the average value per order?

SELECT o.ord_id, SUM(od.total_price) AS order_value
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.ord_id;

# -- Or average across all orders:

SELECT AVG(order_value) AS avg_order_value
FROM (
    SELECT SUM(od.total_price) AS order_value
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS order_totals;

#-- On which dates were the most orders placed?

SELECT order_date, COUNT(*) AS num_orders
FROM orders
GROUP BY order_date
ORDER BY num_orders DESC;

#-- What are the monthly trends in order volume and revenue?

SELECT LEFT(order_date,7) AS month,
       COUNT(*) AS num_orders,
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;

#--- How do order patterns vary across weekdays and weekends?

SELECT 
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(order_date, '%Y-%m-%d')) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(*) AS num_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY day_type;


#--4. Supplier Contribution
#--How many suppliers are there in the database?

SELECT COUNT(*) AS total_suppliers
FROM supplier;

#-- Which supplier provides the most products?

SELECT s.sup_name, COUNT(p.prod_id) AS num_products
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id
ORDER BY num_products DESC;

#--What is the average price of products from each supplier?

SELECT s.sup_name, AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id;

#-- Which suppliers contribute the most to total product sales (by revenue)?

SELECT s.sup_name, SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id
ORDER BY total_revenue DESC;



#-- 5. Employee Performance
#--How many employees have processed orders?

SELECT COUNT(DISTINCT emp_id) AS active_employees
FROM orders;

#--Which employees have handled the most orders?

SELECT e.emp_name, COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id
ORDER BY total_orders DESC;

#--What is the total sales value processed by each employee?

SELECT e.emp_name, SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id
ORDER BY total_sales DESC;

#--What is the average order value handled per employee?

SELECT e.emp_name, AVG(order_value) AS avg_order_value
FROM employees e
JOIN (
    SELECT o.emp_id, o.ord_id, SUM(od.total_price) AS order_value
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS emp_orders ON e.emp_id = emp_orders.emp_id
GROUP BY e.emp_id;




#6. Order Details Deep Dive
#--What is the relationship between quantity ordered and total price?

SELECT quantity, AVG(total_price) AS avg_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity;

#--What is the average quantity ordered per product?

SELECT p.prod_name, AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id;

#--How does the unit price vary across products and orders?

SELECT p.prod_name, MIN(od.each_price) AS min_price, MAX(od.each_price) AS max_price, AVG(od.each_price) AS avg_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id;



